# Generated by Django 5.2.12 on 2026-03-14 10:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hackathon', 'Hackathon'), ('research', 'Research Paper'), ('patent', 'Patent'), ('certificate', 'Certificate')], max_length=20)),
                ('level', models.CharField(choices=[('international', 'International'), ('national', 'National'), ('state', 'State'), ('college', 'College'), ('any', 'Any')], default='any', max_length=20)),
                ('result', models.CharField(choices=[('winner', 'Winner'), ('runner_up', 'Runner Up'), ('participation', 'Participation'), ('published_indexed', 'Published (Indexed)'), ('published_conference', 'Published (Conference)'), ('granted', 'Granted'), ('filed', 'Filed'), ('premium', 'Premium (AWS/Google/MS)'), ('standard', 'Standard (NPTEL/Coursera)'), ('any', 'Any')], default='any', max_length=30)),
                ('points', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Admin')], default='student', max_length=10)),
                ('enrollment_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('hackathon', 'Hackathon'), ('research', 'Research Paper'), ('patent', 'Patent'), ('certificate', 'Certificate')], max_length=20)),
                ('level', models.CharField(choices=[('international', 'International'), ('national', 'National'), ('state', 'State'), ('college', 'College')], default='national', max_length=20)),
                ('result', models.CharField(choices=[('winner', 'Winner'), ('runner_up', 'Runner Up'), ('participation', 'Participation'), ('published_indexed', 'Published (Indexed)'), ('published_conference', 'Published (Conference)'), ('granted', 'Granted'), ('filed', 'Filed'), ('premium', 'Premium (AWS/Google/MS)'), ('standard', 'Standard (NPTEL/Coursera)')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='proofs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('date_of_achievement', models.DateField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('faculty_remarks', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['faculty', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_achievements', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
